// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiskTreeMapStatistics(arg1) {
  return window['go']['main']['App']['DiskTreeMapStatistics'](arg1);
}

export function StartSan(arg1) {
  return window['go']['main']['App']['StartSan'](arg1);
}
