// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiskTreeMapStatistics() {
  return window['go']['main']['App']['DiskTreeMapStatistics']();
}

export function StartSan() {
  return window['go']['main']['App']['StartSan']();
}
