// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DiskTreeMapStatistics():Promise<main.DiskTree>;

export function StartSan():Promise<main.DiskTree>;
