// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DiskTreeMapStatistics(arg1:string):Promise<main.DiskTree>;

export function StartSan(arg1:string):Promise<main.DiskTree>;
